### ISSUE TITLE
global name 'REFRESH_INVERVAL' is not defined

### ISSUE THREAD

**Issue by liuhewei** [seanliang/HighlightWords#16]
Error reported when loading plugin: you can see messages below in console (ctrl + `).
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "HighlightWords in /Users/lhw/Library/Application Support/Sublime Text 3/Installed Packages/HighlightWords.sublime-package", line 139, in on_modified
NameError: global name 'REFRESH_INVERVAL' is not defined
```

Seems that the definition of ['REFRESH_INVERVAL' ](https://github.com/seanliang/HighlightWords/blob/master/HighlightWords.py#L129) should be put outside of the class 'HighlightKeywordsCommand'. (After done this, errors disappear.)

**Comment by xacid** [comment]
This should fix it.
143024e434377a472cc9b485b8683de6d09cfe16

**Comment by seanliang** [comment]
Fixed. Thanks @liuhewei @xacid
